name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: clone submodules
      run: git submodule update --init --recursive

    - name: libraries
      run: sudo apt-get install libsdl2-ttf-dev

    - name: configure
      run: make config

    - name: build
      run: make
